# Generated by Django 6.0.8 on 2026-09-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('RESERVED', 'Зарезервирован'), ('PAID', 'Оплачен'), ('CONFIRMED', 'Подтвержден'), ('CANCELLED', 'Отменен'), ('COMPLETED', 'Выполнен')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
