# Generated by Django 6.0.8 on 2026-08-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_items_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(choices=[("invoice", "Invoice")], max_length=20),
                ),
                ("storage_key", models.CharField(max_length=500)),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ заказа",
                "verbose_name_plural": "Документы заказов",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("document_type", "invoice")),
                        fields=("order", "document_type"),
                        name="unique_invoice_per_order",
                    )
                ],
            },
        ),
    ]
