# Generated by Django 6.0.8 on 2026-09-16 13:06

import apps.accounts.services.user_avatar_upload_path
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.accounts.services.user_avatar_upload_path.AccountService.user_avatar_upload_path),
        ),
    ]
