# Generated by Django 6.0.8 on 2026-09-16 13:06

import imagekit.models.fields
from django.db import migrations

import apps.accounts.services.accounts


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to=apps.accounts.services.accounts.AccountService.user_avatar_upload_path,
            ),
        ),
    ]
