# Generated by Django 6.0.8 on 2026-08-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileDocument",
        ),
    ]
