# Generated by Django 6.0.8 on 2026-09-24 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentwebhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotence_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
