# Generated by Django 6.0.8 on 2026-09-26 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
        ('payments', '0004_paymentrefund'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentrefund',
            name='payments_pa_payment_2735e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentwebhookevent',
            name='payments_pa_provide_1feafd_idx',
        ),
        migrations.DeleteModel(
            name='PaymentWebhookEvent',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_order_i_a76289_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_provide_3e1786_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='external_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('yookassa', 'ЮKassa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Создан (ожидает действия)'), ('succeeded', 'Успешно оплачен'), ('canceled', 'Отклонен/Истек')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='idempotence_key',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider_payment_id',
        ),
        migrations.DeleteModel(
            name='PaymentRefund',
        ),
    ]
