# Generated by Django 6.1 on 2026-08-19 11:58
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations =[
        BtreeGinExtension(),
        TrigramExtension(),
    ]
