# Generated by Django 6.1 on 2026-08-19 12:02

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_add_trgm_extension"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("pc", "шт."), ("kg", "кг."), ("l", "л.")],
                        default="pc",
                        max_length=10,
                        verbose_name="Единица измерения",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        limit_choices_to={"type": "SUPPLIER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["price"], name="idx_product_price"),
                    models.Index(
                        fields=["is_active", "-price"], name="product_active_price_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name"],
                        name="product_name_trgm_idx",
                        opclasses=["gin_trgm_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["description"],
                        name="product_desc_trgm_idx",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
    ]
