# Generated by Django 6.0.8 on 2026-09-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['warehouse', 'product'], name='catalog_sto_warehou_a8e81c_idx'),
        ),
    ]
