# Generated by Django 6.1 on 2026-08-23 17:50

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_username"),
        ("catalog", "0003_warehouse_stock"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="product_active_price_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_name_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="product_desc_trgm_idx",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "price"], name="idx_product_active_price"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass("name", name="gin_trgm_ops"),
                name="product_name_trgm_idx",
            ),
        ),
    ]
