# Generated by Django 6.1 on 2026-08-24 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_username"),
        ("catalog", "0004_remove_product_product_active_price_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="external_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="idx_product_sku"),
        ),
    ]
