# Generated by Django 6.1 on 2026-08-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_username"),
        ("catalog", "0005_warehouse_external_id_alter_product_sku_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("sku", "supplier"), name="unique_sku_per_supplier"
            ),
        ),
    ]
