# Generated by Django 6.1 on 2026-08-25 09:27

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_username"),
        ("catalog", "0006_product_unique_sku_per_supplier"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="warehouse",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="warehouse_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["-created_at"], name="catalog_war_created_cc128b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("name", "supplier"), name="unique_name_per_supplier"
            ),
        ),
    ]
