# Generated by Django 6.0.8 on 2026-08-31 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_pricelistimport"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelistimport",
            name="external_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
