# Generated by Django 6.0.8 on 2026-08-31 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_pricelistimport_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceListImportError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "error_message",
                    models.JSONField(help_text="Описание ошибок валидации"),
                ),
                (
                    "import_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_errors",
                        to="catalog.pricelistimport",
                    ),
                ),
            ],
        ),
    ]
