# Generated by Django 6.0.8 on 2026-08-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_pricelistimporterror"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="unit",
        ),
    ]
