# Generated by Django 6.0.8 on 2026-09-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_remove_product_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelistimport",
            name="finished_at",
        ),
        migrations.AlterField(
            model_name="pricelistimport",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="PriceListImportError",
        ),
    ]
