# Generated by Django 6.0.8 on 2026-09-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_remove_pricelistimport_finished_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelistimport",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("COMPLETED_WITH_ERRORS", "Completed with errors"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
