# Generated by Django 6.0.8 on 2026-09-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_pricelistimport_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelistimport",
            name="processed_rows",
        ),
    ]
