# Generated by Django 6.0.8 on 2026-09-03 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('SUPPLIER', 'Поставщик'), ('BUYER', 'Покупатель')], max_length=150, verbose_name='Тип организации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
