# Generated by Django 6.0.8 on 2026-09-16 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='inn',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='kpp',
            field=models.CharField(default='', max_length=9, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'На рассмотрении'), ('VERIFIED', 'Подтверждено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=50)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'На рассмотрении'), ('ACCEPTED', 'Принято'), ('EXPIRED', 'Истекло'), ('REVOKED', 'Отозвано')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organizations.organization')),
            ],
        ),
    ]
