# Generated by Django 6.0.8 on 2026-09-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_description_organization_inn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='verifization_status',
            new_name='verification_status',
        ),
    ]
